#!/bin/sh
EFF_SUCC=/home/spes/Music/sounds/53099^DingLing.mp3
EFF_ERR=/home/spes/Music/sounds/windows-error-sound-effect-35894.mp3

$*
if (( $? > 0)); then
	playsound $EFF_ERR > /dev/null
else
	playsound $EFF_SUCC > /dev/null
fi
